/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    providers: Provider;
    resources: Resource;
    blog: Blog;
    'pdf-library': PdfLibrary;
    tags: Tag;
    faqs: Faq;
    pages: Page;
    'membership-applications': MembershipApplication;
    'membership-share-log': MembershipShareLog;
    'contact-submissions': ContactSubmission;
    'service-provider-options': ServiceProviderOption;
    committees: Committee;
    events: Event;
    bylaws: Bylaw;
    'service-standards': ServiceStandard;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    providers: ProvidersSelect<false> | ProvidersSelect<true>;
    resources: ResourcesSelect<false> | ResourcesSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    'pdf-library': PdfLibrarySelect<false> | PdfLibrarySelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    'membership-applications': MembershipApplicationsSelect<false> | MembershipApplicationsSelect<true>;
    'membership-share-log': MembershipShareLogSelect<false> | MembershipShareLogSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'service-provider-options': ServiceProviderOptionsSelect<false> | ServiceProviderOptionsSelect<true>;
    committees: CommitteesSelect<false> | CommitteesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    bylaws: BylawsSelect<false> | BylawsSelect<true>;
    'service-standards': ServiceStandardsSelect<false> | ServiceStandardsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Admin users who can manage content
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * HIV service providers in the Middlesex-Somerset-Hunterdon area
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers".
 */
export interface Provider {
  id: number;
  name: string;
  /**
   * URL-friendly version of the name
   */
  slug: string;
  description: string;
  type?: ('FQHC' | 'Hospital' | 'Community' | 'Mental Health' | 'Substance Abuse' | 'Other') | null;
  location: {
    address: string;
    city: string;
    state?: string | null;
    zipCode: string;
    county: 'middlesex' | 'somerset' | 'hunterdon';
  };
  contact: {
    phone: string;
    /**
     * 24-hour hotline (if different from main phone)
     */
    phone24hr?: string | null;
    fax?: string | null;
    email?: string | null;
    website?: string | null;
  };
  hours?: {
    monday?: string | null;
    tuesday?: string | null;
    wednesday?: string | null;
    thursday?: string | null;
    friday?: string | null;
    saturday?: string | null;
    sunday?: string | null;
  };
  services?: {
    medical?:
      | {
          service?: string | null;
          id?: string | null;
        }[]
      | null;
    support?:
      | {
          service?: string | null;
          id?: string | null;
        }[]
      | null;
    prevention?:
      | {
          service?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  eligibility?:
    | {
        requirement?: string | null;
        id?: string | null;
      }[]
    | null;
  ryanWhite?: boolean | null;
  ryanWhiteParts?: ('A' | 'B' | 'C' | 'D')[] | null;
  languages?:
    | {
        language?: string | null;
        id?: string | null;
      }[]
    | null;
  accessibility?:
    | {
        feature?: string | null;
        id?: string | null;
      }[]
    | null;
  insurance?:
    | {
        plan?: string | null;
        id?: string | null;
      }[]
    | null;
  coordinates: {
    lat: number;
    lng: number;
  };
  status: 'active' | 'inactive' | 'pending';
  updatedAt: string;
  createdAt: string;
}
/**
 * Downloadable resources and external links
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources".
 */
export interface Resource {
  id: number;
  title: string;
  /**
   * URL-friendly version of the title
   */
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category:
    | 'testing'
    | 'treatment'
    | 'support'
    | 'prevention'
    | 'legal'
    | 'financial'
    | 'housing'
    | 'living_with_hiv'
    | 'nj_resources'
    | 'federal_websites'
    | 'provider_resources'
    | 'other';
  /**
   * Upload a PDF file (will be stored in Cloudflare R2)
   */
  pdfFile?: (number | null) | Media;
  /**
   * Link to external resource (if no PDF)
   */
  externalLink?: string | null;
  /**
   * Type of resource - internal PDF or external website
   */
  linkType: 'internal_pdf' | 'external_link';
  tags?: (number | Tag)[] | null;
  language: 'english' | 'spanish' | 'both';
  /**
   * Show this resource prominently on the resources page
   */
  featured?: boolean | null;
  publishedDate: string;
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * Tags for organizing resources and blog posts
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: number;
  name: string;
  /**
   * URL-friendly version of the name
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog posts, news, and updates
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  title: string;
  /**
   * URL-friendly version of the title
   */
  slug: string;
  author: string;
  publishedDate: string;
  featuredImage?: (number | null) | Media;
  /**
   * Short summary (max 200 characters) for listing pages
   */
  excerpt: string;
  /**
   * Main blog post content
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  category: 'news' | 'events' | 'updates' | 'stories' | 'community';
  tags?: (number | Tag)[] | null;
  language: 'english' | 'spanish' | 'both';
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Versioned PDF document management
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdf-library".
 */
export interface PdfLibrary {
  id: number;
  title: string;
  file: number | Media;
  description?: string | null;
  /**
   * e.g., 1.0, 2.1, 3.0
   */
  versionNumber: string;
  category: 'forms' | 'reports' | 'guides' | 'policies' | 'bylaws' | 'other';
  status: 'current' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * Frequently Asked Questions organized by category
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * The question to be answered
   */
  question: string;
  /**
   * URL-friendly version of the question (auto-generated)
   */
  slug: string;
  /**
   * Detailed answer to the question (supports rich text formatting)
   */
  answer: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Category for organizing FAQs
   */
  category: 'general' | 'services' | 'planning-council' | 'resources' | 'testing' | 'treatment';
  /**
   * Optional tags for additional filtering
   */
  tags?: (number | Tag)[] | null;
  /**
   * Display order (lower numbers appear first)
   */
  order: number;
  /**
   * Language version of this FAQ
   */
  language: 'english' | 'spanish' | 'both';
  /**
   * Publication status
   */
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Custom pages with flexible content (e.g., Planning Council, About pages)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * URL path for this page (e.g., "planning-council" for /planning-council)
   */
  slug: string;
  /**
   * Main page content
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Short description for SEO meta description (150-160 characters)
   */
  excerpt?: string | null;
  meta?: {
    /**
     * SEO title (if different from page title)
     */
    title?: string | null;
    /**
     * SEO meta description
     */
    description?: string | null;
    /**
     * Social sharing image (Open Graph)
     */
    image?: (number | null) | Media;
  };
  /**
   * Hero image for page header
   */
  featuredImage?: (number | null) | Media;
  /**
   * Display this page in the main navigation menu
   */
  showInNavigation?: boolean | null;
  language: 'english' | 'spanish' | 'both';
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * Planning Council membership applications with status tracking
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-applications".
 */
export interface MembershipApplication {
  id: number;
  fullName?: string | null;
  status?: ('pending' | 'reviewing' | 'approved' | 'rejected') | null;
  firstName: string;
  lastName: string;
  birthMonth?: string | null;
  birthDay?: string | null;
  birthYear?: string | null;
  email: string;
  confirmEmail: string;
  /**
   * Primary phone (auto-filled from cell or home)
   */
  phone?: string | null;
  homePhone?: string | null;
  cellPhone?: string | null;
  bestTimeToCall?: string | null;
  streetAddress: string;
  addressLine2?: string | null;
  city: string;
  state: string;
  zipCode: string;
  country?: string | null;
  isEmployed?: boolean | null;
  employers?: string | null;
  jobTitle?: string | null;
  companyAddress?: string | null;
  companyAddressLine2?: string | null;
  companyCity?: string | null;
  companyState?: string | null;
  companyZipCode?: string | null;
  receivedRyanWhiteServices?: boolean | null;
  gender?: string | null;
  age?: string | null;
  raceEthnicity?: string | null;
  mailingLists?:
    | {
        list?: string | null;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        language?: string | null;
        id?: string | null;
      }[]
    | null;
  diverseExperience?:
    | {
        experience?: string | null;
        id?: string | null;
      }[]
    | null;
  serviceProviders?:
    | {
        provider?: string | null;
        id?: string | null;
      }[]
    | null;
  needsAssistance?: boolean | null;
  assistanceDescription?: string | null;
  whyJoin: string;
  hivExperience: string;
  backgroundExperience?: string | null;
  eligibilityInfo?: string | null;
  membershipCategories?:
    | {
        category?: string | null;
        id?: string | null;
      }[]
    | null;
  experienceInterests?:
    | {
        interest?: string | null;
        id?: string | null;
      }[]
    | null;
  agreedToCommitments: boolean;
  consentGiven: boolean;
  /**
   * Internal notes for reviewing application
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Audit log of membership application share links (who shared what, when).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-share-log".
 */
export interface MembershipShareLog {
  id: number;
  /**
   * The application this share link grants access to.
   */
  application: number | MembershipApplication;
  /**
   * The reviewer who created the share link.
   */
  sharedBy?: (number | null) | User;
  /**
   * When the share link stops working.
   */
  expiresAt: string;
  /**
   * Unique id (jti) of the signed share token this row tracks.
   */
  tokenId?: string | null;
  /**
   * Whether this link has been stopped before its expiry.
   */
  revoked?: boolean | null;
  /**
   * When the link was revoked.
   */
  revokedAt?: string | null;
  /**
   * The reviewer who revoked the link.
   */
  revokedBy?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form messages from the public website
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  fullName?: string | null;
  status?: ('new' | 'in-progress' | 'resolved') | null;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string | null;
  county?: ('middlesex' | 'somerset' | 'hunterdon' | 'other') | null;
  inquiryType: 'services' | 'testing' | 'treatment' | 'support' | 'planning-council' | 'other';
  message: string;
  consentGiven: boolean;
  /**
   * Internal notes for handling this inquiry
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Provider options shown on the membership form (Step 3). Edit here to update the form.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-provider-options".
 */
export interface ServiceProviderOption {
  id: number;
  /**
   * Exact text shown (and saved) for this provider option.
   */
  label: string;
  /**
   * Display order (lower = first).
   */
  order?: number | null;
  /**
   * Uncheck to hide from the form without deleting.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Mailing-list / committee options shown on the membership form (Step 1).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committees".
 */
export interface Committee {
  id: number;
  /**
   * Exact text shown (and saved), e.g. "Planning Council (usually 1st Tuesday of each month 6-8pm)".
   */
  label: string;
  /**
   * Display order (lower = first).
   */
  order?: number | null;
  /**
   * Uncheck to hide from the form without deleting.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Community events, meetings, and activities
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * URL-friendly version of the title
   */
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional image for event listing
   */
  featuredImage?: (number | null) | Media;
  startDate: string;
  /**
   * Optional end date/time for multi-day or timed events
   */
  endDate?: string | null;
  location: {
    type: 'in-person' | 'virtual' | 'hybrid';
    venueName?: string | null;
    address?: string | null;
    city?: string | null;
    state?: string | null;
    zipCode?: string | null;
    /**
     * Zoom/Teams/Virtual meeting link
     */
    virtualLink?: string | null;
  };
  /**
   * Auto-populated from address. You can manually adjust if needed.
   */
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  /**
   * Contact email for questions about this event
   */
  contactEmail?: string | null;
  /**
   * Contact phone for questions
   */
  contactPhone?: string | null;
  /**
   * External RSVP/registration link (if needed)
   */
  rsvpLink?: string | null;
  category: 'planning-council' | 'committee' | 'community' | 'training' | 'health-fair' | 'support-group' | 'other';
  /**
   * Optional tags for filtering events
   */
  tags?: (number | Tag)[] | null;
  status: 'draft' | 'published' | 'cancelled';
  /**
   * Show this event prominently on homepage/events page
   */
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Planning Council Bylaws and organizational documents
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bylaws".
 */
export interface Bylaw {
  id: number;
  /**
   * Bylaws document title (e.g., "Planning Council Bylaws")
   */
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  /**
   * Upload the bylaws PDF document
   */
  document: number | Media;
  /**
   * Document version (e.g., "2024 Revision", "Version 3.0")
   */
  version?: string | null;
  /**
   * Date when these bylaws became effective
   */
  effectiveDate: string;
  /**
   * Brief description of the document or changes in this version
   */
  description?: string | null;
  /**
   * Mark as the current/active version of bylaws
   */
  isCurrent?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * Ryan White Service Standards and quality guidelines
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-standards".
 */
export interface ServiceStandard {
  id: number;
  /**
   * Service standard title (e.g., "Core Medical Services Standards")
   */
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title)
   */
  slug: string;
  /**
   * Upload the service standards PDF document
   */
  document: number | Media;
  /**
   * Category of service standard
   */
  category: 'core' | 'service-delivery' | 'quality' | 'medical' | 'support' | 'prevention' | 'other';
  /**
   * Brief description of what this standard covers
   */
  description?: string | null;
  /**
   * Display order (lower numbers appear first)
   */
  order?: number | null;
  /**
   * Date when this standard was last updated
   */
  lastUpdated: string;
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'providers';
        value: number | Provider;
      } | null)
    | ({
        relationTo: 'resources';
        value: number | Resource;
      } | null)
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'pdf-library';
        value: number | PdfLibrary;
      } | null)
    | ({
        relationTo: 'tags';
        value: number | Tag;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'membership-applications';
        value: number | MembershipApplication;
      } | null)
    | ({
        relationTo: 'membership-share-log';
        value: number | MembershipShareLog;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'service-provider-options';
        value: number | ServiceProviderOption;
      } | null)
    | ({
        relationTo: 'committees';
        value: number | Committee;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'bylaws';
        value: number | Bylaw;
      } | null)
    | ({
        relationTo: 'service-standards';
        value: number | ServiceStandard;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "providers_select".
 */
export interface ProvidersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  type?: T;
  location?:
    | T
    | {
        address?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        county?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        phone24hr?: T;
        fax?: T;
        email?: T;
        website?: T;
      };
  hours?:
    | T
    | {
        monday?: T;
        tuesday?: T;
        wednesday?: T;
        thursday?: T;
        friday?: T;
        saturday?: T;
        sunday?: T;
      };
  services?:
    | T
    | {
        medical?:
          | T
          | {
              service?: T;
              id?: T;
            };
        support?:
          | T
          | {
              service?: T;
              id?: T;
            };
        prevention?:
          | T
          | {
              service?: T;
              id?: T;
            };
      };
  eligibility?:
    | T
    | {
        requirement?: T;
        id?: T;
      };
  ryanWhite?: T;
  ryanWhiteParts?: T;
  languages?:
    | T
    | {
        language?: T;
        id?: T;
      };
  accessibility?:
    | T
    | {
        feature?: T;
        id?: T;
      };
  insurance?:
    | T
    | {
        plan?: T;
        id?: T;
      };
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "resources_select".
 */
export interface ResourcesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  category?: T;
  pdfFile?: T;
  externalLink?: T;
  linkType?: T;
  tags?: T;
  language?: T;
  featured?: T;
  publishedDate?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  author?: T;
  publishedDate?: T;
  featuredImage?: T;
  excerpt?: T;
  content?: T;
  category?: T;
  tags?: T;
  language?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdf-library_select".
 */
export interface PdfLibrarySelect<T extends boolean = true> {
  title?: T;
  file?: T;
  description?: T;
  versionNumber?: T;
  category?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  slug?: T;
  answer?: T;
  category?: T;
  tags?: T;
  order?: T;
  language?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  excerpt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  featuredImage?: T;
  showInNavigation?: T;
  language?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-applications_select".
 */
export interface MembershipApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  status?: T;
  firstName?: T;
  lastName?: T;
  birthMonth?: T;
  birthDay?: T;
  birthYear?: T;
  email?: T;
  confirmEmail?: T;
  phone?: T;
  homePhone?: T;
  cellPhone?: T;
  bestTimeToCall?: T;
  streetAddress?: T;
  addressLine2?: T;
  city?: T;
  state?: T;
  zipCode?: T;
  country?: T;
  isEmployed?: T;
  employers?: T;
  jobTitle?: T;
  companyAddress?: T;
  companyAddressLine2?: T;
  companyCity?: T;
  companyState?: T;
  companyZipCode?: T;
  receivedRyanWhiteServices?: T;
  gender?: T;
  age?: T;
  raceEthnicity?: T;
  mailingLists?:
    | T
    | {
        list?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        language?: T;
        id?: T;
      };
  diverseExperience?:
    | T
    | {
        experience?: T;
        id?: T;
      };
  serviceProviders?:
    | T
    | {
        provider?: T;
        id?: T;
      };
  needsAssistance?: T;
  assistanceDescription?: T;
  whyJoin?: T;
  hivExperience?: T;
  backgroundExperience?: T;
  eligibilityInfo?: T;
  membershipCategories?:
    | T
    | {
        category?: T;
        id?: T;
      };
  experienceInterests?:
    | T
    | {
        interest?: T;
        id?: T;
      };
  agreedToCommitments?: T;
  consentGiven?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "membership-share-log_select".
 */
export interface MembershipShareLogSelect<T extends boolean = true> {
  application?: T;
  sharedBy?: T;
  expiresAt?: T;
  tokenId?: T;
  revoked?: T;
  revokedAt?: T;
  revokedBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  fullName?: T;
  status?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  county?: T;
  inquiryType?: T;
  message?: T;
  consentGiven?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-provider-options_select".
 */
export interface ServiceProviderOptionsSelect<T extends boolean = true> {
  label?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "committees_select".
 */
export interface CommitteesSelect<T extends boolean = true> {
  label?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  featuredImage?: T;
  startDate?: T;
  endDate?: T;
  location?:
    | T
    | {
        type?: T;
        venueName?: T;
        address?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        virtualLink?: T;
      };
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  contactEmail?: T;
  contactPhone?: T;
  rsvpLink?: T;
  category?: T;
  tags?: T;
  status?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bylaws_select".
 */
export interface BylawsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  document?: T;
  version?: T;
  effectiveDate?: T;
  description?: T;
  isCurrent?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-standards_select".
 */
export interface ServiceStandardsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  document?: T;
  category?: T;
  description?: T;
  order?: T;
  lastUpdated?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site-wide settings
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  /**
   * Main hotline/contact number
   */
  hotlineNumber: string;
  /**
   * Main navigation menu items with optional dropdown children
   */
  navigation?:
    | {
        /**
         * Menu item text
         */
        label: string;
        /**
         * Link URL (leave empty if this item has dropdown children)
         */
        url?: string | null;
        /**
         * Open link in new tab
         */
        openInNewTab?: boolean | null;
        /**
         * Child menu items (creates a dropdown menu)
         */
        children?:
          | {
              /**
               * Dropdown item text
               */
              label: string;
              /**
               * Link URL for this dropdown item
               */
              url: string;
              /**
               * Open link in new tab
               */
              openInNewTab?: boolean | null;
              /**
               * Display order within dropdown
               */
              order?: number | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Display order (0 = first, 1 = second, etc.)
         */
        order?: number | null;
        id?: string | null;
      }[]
    | null;
  logo?: (number | null) | Media;
  footerLinks?:
    | {
        label: string;
        url: string;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  socialMedia?: {
    facebook?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
  };
  contactEmail: string;
  /**
   * Enable to show maintenance page
   */
  maintenanceMode?: boolean | null;
  /**
   * Message to display during maintenance
   */
  maintenanceMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  hotlineNumber?: T;
  navigation?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              openInNewTab?: T;
              order?: T;
              id?: T;
            };
        order?: T;
        id?: T;
      };
  logo?: T;
  footerLinks?:
    | T
    | {
        label?: T;
        url?: T;
        openInNewTab?: T;
        id?: T;
      };
  socialMedia?:
    | T
    | {
        facebook?: T;
        twitter?: T;
        instagram?: T;
        linkedin?: T;
      };
  contactEmail?: T;
  maintenanceMode?: T;
  maintenanceMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}